### PR TITLE
Include CloseEvent in on_close call

### LINKED ISSUE #2: Expose close event details?
Currently, `on_close` is a function without any parameters. I would like to access the close event details to retrieve the close code, so it would be nice to have that passed in.

### PR DESCRIPTION
**Pull request by vpzomtrrfrt**
Resolves #2, though this _is_ a breaking change

### CODE REVIEW

**Comment by scratchyone** [comment]
Sorry, just saw this now. This looks great, I'll test this and make sure all the examples still work with this change, but the CloseEvent info should definitely be available. This seems worth a breaking change to me.

**Comment by extrawurst** [comment]
@scratchyone any updates on reviewing, merging and releasing this?

**Comment by scratchyone** [comment]
Thank you so much for your contribution @vpzomtrrfrt, and thanks @extrawurst for reminding me to review it haha. I'll work on some other changes and then publish this as v1.0.0.

**Comment by scratchyone** [comment]
v.1.0.0 including this PR is available on crates.io now.

**Pull request merged**
